version: '3'
services:
  ftp_download_sync:
    container_name: ftp_download_sync
    image: ruby_image
    build: 
      context: ./
      dockerfile: Dockerfile
    networks: 
      - data_network
    volumes:
      - ./config/:/app/config/
      - ./data/in/:/app/data/in/
      - ./data/out/:/app/data/out/
      #- /libis/ftp/LIMO/lirias2/primo_ve/:/ftp_dir/
      - ../../../dCollector/lirias_collector_git/records/primo_ve/:/ftp_dir/

networks:
  data_network:
    driver: bridge
